name: Auto Sync All Branches

on:
  schedule:
    - cron: '0 3 * * *'          # 每天 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Sync default branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh repo sync "${{ github.repository }}" --force

      - name: Sync ALL upstream branches
        run: |
          set -e
          git remote add upstream https://github.com/Vespa314/chan.py.git
          git fetch upstream --prune
          for b in $(git for-each-ref --format='%(refname:short)' refs/remotes/upstream \
                     | grep -v 'upstream/HEAD' \
                     | sed 's|^upstream/||'); do
            echo "▶ syncing $b"
            git push -f origin "refs/remotes/upstream/$b:refs/heads/$b"
          done
